packages:
  - "placeholder/*"

catalogs:
  lint:
    "@eslint/js": "^9.25.1"
    "@stylistic/eslint-plugin": "^5.0.0"
    "eslint": "^9.25.1"
    "eslint-plugin-unused-imports": "^4.1.4"
    "typescript-eslint": "^8.31.1"
  runtime:
    "consola": "^3.4.2"
    "dotenv-cli": "^8.0.0"
    "ky": "^1.8.1"
    "tsx": "^4.20.3"
    "yargs": "^18.0.0"
  typescript:
    "@types/node": "^24.0.3"
    "openapi-typescript": "^7.8.0"
    "@types/yargs": "^17.0.33"

